### PR TITLE
Add guidance on licensing

### LINKED ISSUE #802: Make a list of ok licences for us to publish under
[Our founding principles](https://about.publiccode.net/organization/mission.html#founding-principles) say:

> We publish under licenses approved by the Open Source Initiative or Creative Commons licenses that do not limit commercial reuse.

At the moment, we scramble to identify an acceptable licence each time we publish our content on a new 3rd party platform (for example our recent publication of our Creative Commons Global Summit workshop video on YouTube).

Since none of us are professional experts in open licenses, it would be helpful to add a short list of licenses we commonly use **and why** (insteaad of other similar ones) somewhere to About, so we're not doing original research each time.

### PR DESCRIPTION
**Pull request by Ainali**
Fixes #802

-----
[View rendered contributor-guides/for-staff.md](https://github.com/publiccodenet/about/blob/ok-licenses/contributor-guides/for-staff.md)

### CODE REVIEW

**Comment by clausmullie** [comment]
Jan - I turned it into some fuller text. How do you feel about this?

**Comment by Ainali** [comment]
I like it a lot, great change @clausmullie !

**Review by ericherman — CHANGES_REQUESTED** [review]
There is a third exception I can think of and that would be building on an existing work. There may be others. Thus, I think we need to add a bit of looseness here, for instance:

"There are two common exceptions to this."

**Comment by Ainali** [comment]
That is not really an exception in the same sense, because in that case you don't even have the copyright in the first place, allowing you to choose the license freely.

But yes, there may be other exceptions. Perhaps we just add to the list when we discover them?

**Comment by ericherman** [comment]
> That is not really an exception in the same sense, because in that case you don't even have the copyright in the first place, allowing you to choose the license freely.

(Future readers: Jan and I both know that each author retains the copyright on their portion, and it is certainly possible to mix licenses.)

Sure, it is different, but each of the other two cases are different from the general case, thus I'm not convinced it is *so* different as to not count. 

> But yes, there may be other exceptions. Perhaps we just add to the list when we discover them?

Perhaps. I think I'd lean toward the looser (more weasel-wordy?) approach: seems lower maintenance and doesn't change the guidance that we have a default, there are some obvious exceptions staff are likely to encounter. That said, I'm not going to push hard for it.

**Comment by Ainali** [comment]
Fair points.

> I think I'd lean toward the looser (more weasel-wordy?) approach

I'm happy with changes Claus made, do you feel those are enough?

**Review by ericherman — APPROVED** [review]

**Pull request merged**
