### PR TITLE
Flesh out codebase activities page

### PR DESCRIPTION
**Pull request by clausmullie**
Add in content developed for the codebase we are working to incubate 

Works towards #428 

-----
[View rendered activities/codebase-stewardship/activities.md](https://github.com/publiccodenet/about/blob/Flesh-out-codebase-activities-page/activities/codebase-stewardship/activities.md)

### CODE REVIEW

**Comment by clausmullie** [comment]
@ElenaFdR @ericherman @Ainali would it make sense to have this content here? 

I'm thinking it may even make sense to reorder and explain 'codebase/ecosystem' level first, and then say what we do at the codebase level?

**Comment by ericherman** [comment]
@clausmullie I think we want this content in "about" and this seems like as reasonable a place as any. 

As for the ordering, I do not have a strong opinion .... Maybe try framing the ecosystem stuff first and see how it reads?

**Comment by Ainali** [comment]
I like the way it turns this page from a simple list to something that is more readable and puts all the activities in a context. If we move codebase/ecosystem up, I believe it would be good to put them and the top bullet point list under a new top heading called Overview or something similar. That would make the overall outline a bit clearer (with only 5 H2 tags).

**Comment by clausmullie** [comment]
I'm left wondering how this fits in with our desired balance of 'http = marketing' and 'about = functional' 

Is this information too much on the marketing side? What do you think @ElenaFdR  and @bvhme?

**Comment by clausmullie** [comment]
I have made an attempt to reorder and shorten. We may want to resolve #427 before merging this, particularly in about/activities/codebase-stewardship/goals.md

**Comment by ericherman** [comment]
> I have made an attempt to reorder and shorten. We may want to resolve #427 before merging this, particularly in about/activities/codebase-stewardship/goals.md

Let's not block this waiting for https://github.com/publiccodenet/about/issues/427 , instead let's plan to adjust this, if needed, after 427.

**Pull request merged**
