### PR TITLE
Define Public Code

### PR DESCRIPTION
**Pull request by bvhme**
I've made a definition for the term **Public Code**.

Please let this PR serve as a place for discussion around this topic, as I feel it is quite core to what we do.

### CODE REVIEW

**Comment by bvhme** [comment]
@nebster What do you think about involving some Advisors in this defining process?

**Comment by nebster** [comment]
We should definitely get our Advisors in here for review.  I would in the definition also mention the recognition of software as Public Infrastructure, which already has evolved a set of regulatory constraints in society.  Also perhaps the idea that Public software is also a process, that involves long-term institutional commitment and potentially deliberative development or at least deliberative functional definition.

**Comment by bvhme** [comment]
Thanks @nebster, the question I have for you is, yes those seem like important aspects, however, is the current definition unusable if those elements are not in there, if not I'd like for us to note them as feature requests (as they might need their own glossary items)

**Comment by bvhme** [comment]
@nebster another ping on the above :) I'd like to move this forward.

**Pull request merged**
