### PR TITLE
DRAFT: tool and email naming conventions

### PR DESCRIPTION
**Pull request by ElenaFdR**
Still missing:
- [x] table with naming conventions
- [x] Are there existing list conventions for "all-codebasename@lists.publiccode.net (all-signalen@lists.publiccode.net) or subgroup-codebase@"? If so, we should follow those.
- [x] folder index (@demkodo, what else do you think will go here?)

-----
[View rendered activities/tool-management/tool-and-email-naming-conventions.md](https://github.com/publiccodenet/about/blob/namespace-conventions/activities/tool-management/tool-and-email-naming-conventions.md)

### CODE REVIEW

**Comment by demkodo** [comment]
No existing list conventions for mailing lists yet, but once we get to that point the convention as mentioned here should be followed.

**Comment by demkodo** [comment]
No comments on the folder index at this moment

**Comment by bvhme** [comment]
Okay, some feedback to try and simplify this and make it a bit more scalable:

* I think every email adress which is `*@publiccode.net` is internal and should go to staff and officials only.
* Emails to `*@publiccode.net` should go to people or to internal mailinglists (which can be shared email adresses).
* I think any tool or machine use should use a `*@[subdomain].publiccode.net`.
* Things like servers etcetera should use internal distrubution lists as well. These can be lists with no subscribers and archiving turned on if unmonitored. Consider giving these a standardised prefix.
* I'd standardise on the use of `.` versus `-` in email adresses and not use them interchangably.

Very good! Let's try to make it make a bit less hacky.

**Comment by bvhme** [comment]
Due to me accidentally merging this to master, we might need to squash this PR when merging it.

**Pull request merged**
