### PR TITLE
decap and complete job titles

### PR DESCRIPTION
**Pull request by MirjamvT**

### CODE REVIEW

**Comment by bvhme** [comment]
Do we want to call these officers?

**Comment by MirjamvT** [comment]
that seems the common terminology. may not be the greatest. i do feel it needs a noun to be a complete job title. better suggestions welcomed.

**Comment by bvhme** [comment]
For completeness, the reason to go with the british style Chief X was because we didn't yet know whether these should be _officer_ or _director_.

But it is fine to go with this and change if we need to.

**Comment by MirjamvT** [comment]
officer is fine with  me too. guess Ben and Elena have good input on this

Best regards,
Mirjam van Tiel
+31 6 4662 8454

**Pull request merged**
