### PR TITLE
Add logframe to organization

### PR DESCRIPTION
**Pull request by lscheske**
* created new file with the final logical framework for December 2020 - March 2021, as approved by board and executive team - naming this measurable goals for accessibility
* added this to organization folder
* added link from index.md
* grouped items in first list in index.md
* added descripition & link from mission.md to link this with the published priorities

-----
[View rendered organization/index.md](https://github.com/publiccodenet/about/blob/add-logframe-organization/organization/index.md)
[View rendered organization/measurable-goals.md](https://github.com/publiccodenet/about/blob/add-logframe-organization/organization/measurable-goals.md)
[View rendered organization/mission.md](https://github.com/publiccodenet/about/blob/add-logframe-organization/organization/mission.md)

### CODE REVIEW

**Comment by lscheske** [comment]
Is there a way to format the measurable-goals.md so it doesn't look so disastrous?  i.e. so the baseline, target, and means of verification indent to the same level as the title of the indicator, AND remove the white lines between them?

**Comment by AlbaRoza** [comment]
Maybe converting it to PDF? @lscheske

**Comment by lscheske** [comment]
I think I got it to work now! Still doesn't look very nice, Travis/MD be damned!

**Comment by bvhme** [comment]
This content looks good!

Also, I'd advise against using **strong** this way, it makes it harder to scan the content since it's used out of flow. That the words there are repetitive will give enough structure. Also, having this many structural elements trying to grab your attention at the same time makes it harder to understand what is going on.

In general I'd advice to apply a less is more attitude to things like this :) If we really need a design solution and would be willing to take on the maintenance of it, it should probably be done in the theme.

**Review by bvhme — APPROVED** [review]

**Review by bvhme — APPROVED** [review]

**Pull request merged**
