### PR TITLE
New information hierarchy, about guides and content type

### PR DESCRIPTION
**Pull request by bvhme**
In order to have a simpler and easier to understand about repository we worked on improving the content types and hierarchy.

See the guides in the `/activities/documentation/` folder for more information.

### CODE REVIEW

**Comment by bvhme** [comment]
Perhaps we can work with @nebster and @clausmullie today to merge this.

**Comment by ElenaFdR** [comment]
Hey, I've finished reviewing this. It looks good! The only thing left to do is extract how we talk about the About and put it into a separate guide.

**Comment by ElenaFdR** [comment]
Upon examination, this page about About models all of the rules for how to refer to About: https://github.com/publiccodenet/about/blob/hierarchie/activities/documentation/index.md

**Comment by bvhme** [comment]
Yes. In order to push back confusion we can stil choose to pick a different name for this, although I think about is pretty much what it is. 'Docs' or 'documentation' comes to mind.

**Pull request merged**
