### PR TITLE
Move pillar content to new indexes

### PR DESCRIPTION
**Pull request by Ainali**
Solves #647.
Related content community calls, supporting governance and product 
assets moved along at the same time as the belong together.

-----
[View rendered activities/codebase-stewardship/activities.md](https://github.com/publiccodenet/about/blob/pillar-subpages/activities/codebase-stewardship/activities.md)
[View rendered activities/codebase-stewardship/community/community-calls/index.md](https://github.com/publiccodenet/about/blob/pillar-subpages/activities/codebase-stewardship/community/community-calls/index.md)
[View rendered activities/codebase-stewardship/community/community-calls/post-process-community-call.md](https://github.com/publiccodenet/about/blob/pillar-subpages/activities/codebase-stewardship/community/community-calls/post-process-community-call.md)
[View rendered activities/codebase-stewardship/community/community-calls/preparing-community-call.md](https://github.com/publiccodenet/about/blob/pillar-subpages/activities/codebase-stewardship/community/community-calls/preparing-community-call.md)
[View rendered activities/codebase-stewardship/community/community-calls/running-community-call.md](https://github.com/publiccodenet/about/blob/pillar-subpages/activities/codebase-stewardship/community/community-calls/running-community-call.md)
[View rendered activities/codebase-stewardship/community/index.md](https://github.com/publiccodenet/about/blob/pillar-subpages/activities/codebase-stewardship/community/index.md)
[View rendered activities/codebase-stewardship/community/supporting-governance/governance-template.md](https://github.com/publiccodenet/about/blob/pillar-subpages/activities/codebase-stewardship/community/supporting-governance/governance-template.md)
[View rendered activities/codebase-stewardship/community/supporting-governance/index.md](https://github.com/publiccodenet/about/blob/pillar-subpages/activities/codebase-stewardship/community/supporting-governance/index.md)
[View rendered activities/codebase-stewardship/index.md](https://github.com/publiccodenet/about/blob/pillar-subpages/activities/codebase-stewardship/index.md)
[View rendered activities/codebase-stewardship/product-marketing/index.md](https://github.com/publiccodenet/about/blob/pillar-subpages/activities/codebase-stewardship/product-marketing/index.md)
[View rendered activities/codebase-stewardship/product-marketing/product-assets-for-early-incubation.md](https://github.com/publiccodenet/about/blob/pillar-subpages/activities/codebase-stewardship/product-marketing/product-assets-for-early-incubation.md)
[View rendered activities/codebase-stewardship/quality/index.md](https://github.com/publiccodenet/about/blob/pillar-subpages/activities/codebase-stewardship/quality/index.md)
[View rendered activities/codebase-stewardship/support/index.md](https://github.com/publiccodenet/about/blob/pillar-subpages/activities/codebase-stewardship/support/index.md)
[View rendered activities/workshops/governance-game/index.md](https://github.com/publiccodenet/about/blob/pillar-subpages/activities/workshops/governance-game/index.md)

### CODE REVIEW

**Comment by bvhme** [comment]
I was having the exact opposite urge with a lot of these things. I was thinking we're creating silo's that are quite strong and was getting confused by the ever more nested nature of activities.

There is a question here on how defined we want the roles of these things to be, and what is necessary.

For example, I was thinking that nesting 'community calls' in 'codebase stewardship' was already creating a situation where we limit their applicability.

Would you be okay with me making another proposal based on your work here?

Thanks

**Comment by Ainali** [comment]
> Would you be okay with me making another proposal based on your work here?

All proposals are welcome! To expand a little: we have more templates and resources that we would like to add to about, but I could not find a natural place for them on the pages as they looked today. If you can find another way to make it easy to add more resources that might be mostly related to a specific pillar, then I am all for it.

**Comment by bvhme** [comment]
I think the main thing here is that I don't think the pillars, and whom thakes ownership over them, should reflect in a hierarchical structure of who takes ownership over what documentation. So I think the main thing here is that the activities are all on the same level and then we can use the explanations of the pilars to guide people to the right place.

Otherwise we'll develop silo's and won't be able to share processes across them. I'll go make a pull request.

**Comment by Ainali** [comment]
> For example, I was thinking that nesting 'community calls' in 'codebase stewardship' was already creating a situation where we limit their applicability.

Well, if the activities are different, then we can either have content in different places, or we can have it in one place, but with nesting in the actual content. For this example, it would end up in a lot of things like "if it is a Foundation call, then X, if it is Standard call, then Y". So that would make it easier to find for those who are not working with it (while not helping those that do), and more confusing to exececute for everyone.

**Comment by bvhme** [comment]
I would say that in your example that we have a community call that is shared and then two implementations, instead of two different version.

The challenge here is that we need to make sure we don't split up all of our actions according to our people. That does not scale. So wherever we can we need to make sure we can build on and use the same resources. This means that if any piece of documentation is useful in two cases it should be linked from both.

**Comment by bvhme** [comment]
I think the cutoff should be, if something is can only meaningfully be done inside another activity it should be nested. Otherwise it should be shared.

For example 'codebase auditing' can be done outside of stewardship, and we might want to do that, so it should live top level.

**Pull request closed without merging**
