### PR TITLE
Onboarding

### LINKED ISSUE #114: Where do we store team rituals?
Do we create a `/processes` folder?

### PR DESCRIPTION
**Pull request by ericherman**
Add some key onboarding tasks for Foundation new hires. Closes #114 and #135.

### CODE REVIEW

**Comment by ElenaFdR** [comment]
Hey, I've just found a potential alternative home for this information:
https://github.com/publiccodenet/about/blob/develop/contributor-guides/for-staff.md

If so, then we could change the trainings page back to its original form. (@bvhme has strong views on this!)

**Comment by bvhme** [comment]
Ooooh, good spot @ElenaFdR!

Yeah, this seems like a great fit for a 'contributor guide for staff'.

Also, that file is sad :/

On side notes:

* if this is in activities I think it needs to be with the 'recruitment' process since there it is an integrated process with that (e.g. the one will never happen without the other) and not a separate process.
* the 'trainings' was meant as the trainings we can give, in or outside of our organisation, 'learning' should be an integral part of every process, and perhaps an activity in it's own right but then should perhaps have a different spin to it (e.g. individual exploration)

**Comment by ericherman** [comment]
As @ElenaFdR points out, this content could live with "for-staff.md" ... and given how *sad* that page is, I figure it's nice to "cheer it up" a bit.

Please review the latest.

**Comment by ericherman** [comment]
Okay, since contributor-guides/index is itself a yet-to-be-linked page, I linked directly to it from organization/index under the "how we approach our work" section.

**Comment by ElenaFdR** [comment]
@ericherman I'm merging this now, so that it doesn't have to wait til you're back.

**Pull request merged**
