### PR TITLE
Add stewardship proposal template

### PR DESCRIPTION
**Pull request by clausmullie**
Add codebase stewardship proposal template
-----
[View rendered activities/codebase-stewardship/stewardship-proposal-template.md](https://github.com/publiccodenet/about/blob/add-stewardship-template/activities/codebase-stewardship/stewardship-proposal-template.md)

### CODE REVIEW

**Comment by clausmullie** [comment]
Not 100% sure about the placement of this on the index. @Ainali what do you think?

**Comment by Ainali** [comment]
Agreed. perhaps the last three bullet points can be put under a new heading "Useful resources"?

**Comment by clausmullie** [comment]
I like it. Done!

**Comment by clausmullie** [comment]
This template works towards  #341

**Comment by ElenaFdR** [comment]
I suggest merging:

## What codebase stewardship is
And 
## How codebase stewardship works

Into one category:

## Introduction to codebase stewardship

**Pull request merged**
