### PR TITLE
Update financial-model.md

### PR DESCRIPTION
**Pull request by lscheske**
* remove references to founding members
* say that we're currently wholly philanthropically funded & link to philanthropy policy page
* make distinction between now and future

Solves #787

-----
[View rendered organization/financial-model.md](https://github.com/publiccodenet/about/blob/update-financial-model/organization/financial-model.md)

### CODE REVIEW

**Review by ElenaFdR — COMMENTED** [review]
Much cleaner, and long overdue! I've made 1 language suggestion.

**Review by bvhme — APPROVED** [review]
Looks good to me :)

**Comment by lscheske** [comment]
> Looks good to me :)

Travis is blocking something here that is beyond my ability to fix. Could you take a look @bvhme ?

**Comment by bvhme** [comment]
Travis needed to be restarted, that website was down when it tested.

**Pull request merged**
