### PR TITLE
Add community assets

### PR DESCRIPTION
**Pull request by Ainali**
Solves #627. Based on the work with product assets, two workshops were held two 
create this ordered list.

-----
[View rendered activities/codebase-stewardship/community-assets.md](https://github.com/publiccodenet/about/blob/community-assets/activities/codebase-stewardship/community-assets.md)
[View rendered activities/codebase-stewardship/index.md](https://github.com/publiccodenet/about/blob/community-assets/activities/codebase-stewardship/index.md)
[View rendered activities/codebase-stewardship/product-assets-for-early-incubation.md](https://github.com/publiccodenet/about/blob/community-assets/activities/codebase-stewardship/product-assets-for-early-incubation.md)

### CODE REVIEW

**Comment by Ainali** [comment]
> I wonder if the list would be more useful if it was truncated.

That is a great question that we discussed quite a bit. In the end, we felt that keeping it all is still useful, because it gives an overview of assets over time. The completeness can be reassuring in that something wasn't missing because of an oversight, but was actively considered and deprioritized.

**Comment by ElenaFdR** [comment]
Nice, clear list! I have a question about its usage: do you anticipate using it at the same time, with the same people as the product asset list? This list looks like it has similar items in a slightly different order - would one list take precedence?

**Comment by Ainali** [comment]
> I have a question about its usage: do you anticipate using it at the same time, with the same people as the product asset list? 

Possibly, but not necessarily.

> This list looks like it has similar items in a slightly different order - would one list take precedence?

No, as they have different purposes. But we realized this tension as well and envision a "grand unified theory" when we have similar lists for all pillars. They could then be put into the same matrix and we could get a sort of weighted result: "If you do X, it has high impact on two pillars and medium on one, but if you do Y it only have medium impact on one pillar, and no impact on the others". This could be a list that takes precedence, but we are not there yet.

**Comment by ElenaFdR** [comment]
I suggest you establish a formal relationship between this and the product assets, so that they're not just each further reading on the other. This would provide context for someone who finds one while looking for the other. A one sentence explanation of the fact that these lists are tools to help codebases with different goals identify the right order for them would probably work.

**Comment by Ainali** [comment]
> This would provide context for someone who finds one while looking for the other. A one sentence explanation of the fact that these lists are tools to help codebases with different goals identify the right order for them would probably work.

This is not intended as tools for codebases, but tools for codebase stewards, and to us it will be fairly obvious which one is which (I mean, it is in the H1).

**Comment by ElenaFdR** [comment]
The codebase stewards may be the main audience, but they probably won't be the only audience. This is because it's on the internet so that others can potentially learn from and be inspired by it, and we already know (because they tell us) that people deliberately read our stuff before meetings with us (including quoting obscure bits of About).

**Comment by Ainali** [comment]
Feel free to come with a suggestion on what would solve this for you. I am hesitant because there are no dependencies between the two a reader _need_ to be aware of. To me they are independent "siblings" which I feel the Further reading is giving due weight.

**Pull request merged**
