### PR TITLE
Add new tools

### PR DESCRIPTION
**Pull request by demkodo**
Hi guys, new tools added to tool management and renamed tool management to "tool management and guidance". Ready to receive feedback and suggestions :) 

-----
[View rendered activities/tool-management/index.md](https://github.com/publiccodenet/about/blob/add-new-tools/activities/tool-management/index.md)
[View rendered activities/tool-management/podbean.md](https://github.com/publiccodenet/about/blob/add-new-tools/activities/tool-management/podbean.md)
[View rendered activities/tool-management/streamyard.md](https://github.com/publiccodenet/about/blob/add-new-tools/activities/tool-management/streamyard.md)

### CODE REVIEW

**Comment by bvhme** [comment]
Yay, this is good content!

Can I suggest that these should be in the activity 'podcast`? So in the folder /activities/podcast/`. That way we can keep the content around specific activities together in stead of organizing them by who is involved.

**Comment by Ainali** [comment]
> Can I suggest that these should be in the activity 'podcast`? So in the folder /activities/podcast/`. That way we can keep the content around specific activities together in stead of organizing them by who is involved.

I like that! So activities Podcast and Livestream rather than focusing on tools. That way we can add some of our best practices to it in the same place.

**Comment by demkodo** [comment]
Travis complains about something I haven't touched:

 ./_site/activities/communication/community-discussions.html

  *  External link https://discuss.publiccode.net/ failed: response code 0 means something's wrong.

It's possible libcurl couldn't connect to the server or perhaps the request timed out.
Sometimes, making too many requests at once also breaks things.
Either way, the return message (if any) from the server is: Couldn't resolve host name

  *  External link https://discuss.publiccode.net/u/discobot/summary failed: response code 0 means something's wrong.

             It's possible libcurl couldn't connect to the server or perhaps the request timed out.

             Sometimes, making too many requests at once also breaks things.

             Either way, the return message (if any) from the server is: Couldn't resolve host name

htmlproofer 3.15.3 | Error:  HTML-Proofer found 2 failures!

**Comment by demkodo** [comment]
There was an issue with "discuss.publiccode.net" --> "The site at https://discuss.publiccode.net/ has experienced a network protocol violation that cannot be repaired." - the site and machine were down, no idea why. I rebooted the instance, checked for updates (and ran a Docker update which is needed to run Discourse). Everything is up and running again but it seems there is some latency and Travis keeps hitting the same wall. I'll keep an eye on it and rerun the build later today - over & out for now

**Comment by demkodo** [comment]
And again something I haven't touched and is also reachable, very annoying:
- ./_site/activities/communication/pitching.html

External link https://about.publiccode.net/organization/mission.html#founding-principles failed: got a time out (response code 0)

htmlproofer 3.15.3 | Error:  HTML-Proofer found 1 failure!

The command "./script/cibuild.sh" exited with 1.
cache.2

store build cache

**Comment by felixfaassen** [comment]
Build errors are cause by a bug in MD lint see my issue and fix here: #737

**Comment by demkodo** [comment]
It passed! Aww yiiiiiissssssss :100:

**Review by Ainali — APPROVED** [review]
Good, I can build on this!

**Comment by ElenaFdR** [comment]
Does [this page](https://about.publiccode.net/organization/data-processing-tools.html) need to be updated as part of this PR? Do these tools collect user information that we have access to?

**Comment by ElenaFdR** [comment]
Would it be useful to add a subheading to the 'tool management and guidance' index with a list of all tools we currently have guidance for, regardless of their parent folder? (Like StreamYard and Podbean?)

**Comment by demkodo** [comment]
> Would it be useful to add a subheading to the 'tool management and guidance' index with a list of all tools we currently have guidance for, regardless of their parent folder? (Like StreamYard and Podbean?)

You mean that I make a subheading called "tools" and list of all tools we use here, including Mattermost (which is also mentioned in 'communication', Jitsi, G-suite mail, Odoo, Podbean, etc?

**Comment by demkodo** [comment]
> Does [this page](https://about.publiccode.net/organization/data-processing-tools.html) need to be updated as part of this PR? Do these tools collect user information that we have access to?

Here you mean if G-suite and Tentoo has access to user info? The answer is yes, obviously. What do you need me to update here? We are already pointing to their GDPR policies. This also reminds me that I never heard back from Opus VL re; GDPR, glad we cancelled our account there. Thanks!

**Comment by demkodo** [comment]
working on this PR so please ignore Travis' whining for now :) Will finish tomorrow and looking into the failed builds then, WIP!

**Comment by demkodo** [comment]
Changed the location of the files, and the links work in the index, but Travis is not allowing it, and I'm not sure why. Thanks in advance for assistance :)

- ./_site/activities/index.html

```
  *  internally linking to live-streaming/streamyard.md, which does not exist (line 145)
<a href="live-streaming/streamyard.md">Live streaming</a>
  *  internally linking to podcasts/podbean.md, which does not exist (line 151)
<a href="podcasts/podbean.md">Podcasts</a>
```

**Review by Ainali — APPROVED** [review]
Good to go!

**Pull request merged**
