### PR TITLE
Resources to explain what stewardship is

### PR DESCRIPTION
**Pull request by Ainali**
more commits to come

### CODE REVIEW

**Comment by clausmullie** [comment]
## supporting notes

@Ainali and I, helped by feedback from @bvhme and @nebster, drafted this set of resources to help explain codebase stewardship. It tries to assume as little knowledge as possible, and build modular components for anyone to use. 

## Open questions:

- [ ] does community steward include community around just the codebase, or also the components
- [ ] include or exclude final point on open source in codebases-scale.md, as one could theoretically do codebase stewardship in a closed environment 
- [ ] if these are the components, where do we put the explanation? it seems to me the graphics would be quite striking and most effective in presented in a single annotated stream (perhaps an idea for a short animated video?)

**Comment by clausmullie** [comment]
We should also check how this pull request might work towards #473 and tangentially towards #281

**Comment by clausmullie** [comment]
Input from call with Ryan and testing the explanation on students:
- [ ] add a diagram of a gitflow fork?
- [ ] make more explicit software as a process

**Comment by ElenaFdR** [comment]
Merge #534 for proofreading of this PR before merging this PR.

**Comment by ElenaFdR** [comment]
From convo with @nebster: the narrative that should accompany a diagram of the forking model is:
during the industrial revolution, people understood how the assembly line led to exponential increase of productivity. Much harder in current industrial revolution for people to conceptualize/visualize/understand how parallelized code production is also exponentially improving productivity

**Comment by bvhme** [comment]
Hey, what is the status on this, is it worth merging this or should it really be improved before we can start using it?

**Pull request merged**
