### PR TITLE
Delete community-discussions.md

### PR DESCRIPTION
**Pull request by demkodo**
-----
[View rendered activities/communication/community-discussions.md](https://github.com/publiccodenet/about/blob/Remove-Discourse/activities/communication/community-discussions.md)

### CODE REVIEW

**Comment by ElenaFdR** [comment]
This closes #763.

**Review by bvhme — APPROVED** [review]
Great update.

**Comment by ElenaFdR** [comment]
Yo, this PR wasn't complete. There's still a link on activities/tool-management/tool-and-email-naming-conventions.md.

**Comment by bvhme** [comment]
Odd that the tests succeeded then... I'll research that later. But that seems like a good bugfix and let's reopen the issue.

**Comment by bvhme** [comment]
Ah, it was just text, not a link! I see that's why the tests succeeded.

**Pull request merged**
