### PR TITLE
Add instructions for online gaming

### PR DESCRIPTION
**Pull request by Ainali**
Solves #683

-----
[View rendered activities/supporting-codebase-governance/game/run-governance-game-workshop.md](https://github.com/publiccodenet/about/blob/online-governance-game/activities/supporting-codebase-governance/game/run-governance-game-workshop.md)

### CODE REVIEW

**Comment by Ainali** [comment]
@felixfaassen Yes, good point. But also, we don't really have something generic set up in Miro yet. When we do, we can add that link as well.

**Comment by Ainali** [comment]
> Is there a way we can open up that template?

Probably. But I am not sure where it should be placed.

**Comment by bvhme** [comment]
If you put it on the Media drive you can set it to public (which I see you've done with a test file) and then you need to 'generate a public link' for it. I've done that with your test file which I can now open in private mode:

<https://docs.google.com/presentation/d/1FfIuVD3M-EXfcbruKlgdTDkBlDti9RJQmPYcRJ2tQoA/edit#slide=id.g7f69cf5c01_0_161>

**Comment by Ainali** [comment]
> If you put it on the Media drive you can set it to public 

Do we want it just in the root or should that folder have a structure that mirrors About? (The test file was put there in a hurry during a session when I realized the participants couldn't access the other file and should probably be deleted.)

**Comment by bvhme** [comment]
That sounds like a good idea!

**Comment by Ainali** [comment]
> That sounds like a good idea!

Which one of them?

**Comment by bvhme** [comment]
A stucture that mirrors about will probably be easiest to deal with if we get a ton of files, otherwise a file in the root might be fine as well. I don't know and we can move them I think without breaking the link. So either way is fine for now.

**Pull request merged**
