### PR TITLE
Added github for newcomers' guide

### PR DESCRIPTION
**Pull request by himanshu007-creator**
This solves #704 

-----
[View rendered contributor-guides/for-staff.md](https://github.com/himanshu007-creator/about/blob/patch-1/contributor-guides/for-staff.md)

### CODE REVIEW

**Review by Ainali — DISMISSED** [review]
This looks good, thanks for your contribution!

**Review by ericherman — CHANGES_REQUESTED** [review]
Good link idea.

Nit-pick: the text "[take some basic training]" could be made more welcoming, perhaps something along the lines of "review [GitHub for newcomers]" or similar.

**Review by himanshu007-creator — COMMENTED** [review]
hi @ericherman , made the changes as suggested🙂

**Review by bvhme — APPROVED** [review]
Great addition, this will surely help.

**Review by ericherman — APPROVED** [review]

**Comment by ElenaFdR** [comment]
Travis is breaking on a link that works in the browser.

**Comment by ericherman** [comment]
Sorry for the long delay, it's merged now. Thanks @himanshu007-creator !

**Comment by himanshu007-creator** [comment]
> Sorry for the long delay, it's merged now. Thanks @himanshu007-creator !

Np , thanks for the opportunity!

**Pull request merged**
