### PR TITLE
Conway's Law

### PR DESCRIPTION
**Pull request by AlbaRoza**
Giving more context about our communication values as a Foundation.

-----
[View rendered activities/procurement/principles.md](https://github.com/publiccodenet/about/blob/AlbaRoza-patch-1/activities/procurement/principles.md)

### CODE REVIEW

**Comment by ElenaFdR** [comment]
Hello! I like the idea of adding Conway's Law, though we might then need to explain what we're doing to circumvent it. 
What's your logic for adding it to the procurement principles, rather than the [communications principles](https://about.publiccode.net/activities/communication/communication-principles.html)?

**Comment by AlbaRoza** [comment]
@ElenaFdR Yeah, I just published it there because, honestly, I read the procurement section before the communication one. However, I think you expressed it very well: this is our way of thinking and therefore, it's also one of our communication principles.

**Comment by ElenaFdR** [comment]
@AlbaRoza Can you update this PR so Conway's Law is added to the communication principles, not the procurement principles?

**Comment by Ainali** [comment]
I believe one can look at Conway's law in different ways. It seems to have originated as a warning, or explanation, to why systems became copies of their communication structure. However, I think there might be room to interpret it in a positive way as well. As we carefully have designed our communication principles in a way that we like our organization to be, it is also possible for us to produce artefacts inline with those. 

But that being said, I think it would suit better as a reference in a blogpost that expands on our beliefs that underlies the communication principles than in the principles itself, where they to me feel rather odd.

**Comment by bvhme** [comment]
Hey @ElenaFdR, @AlbaRoza, how do you view this pull request now, should this be a part of our communications principles?

I'm a bit on the fence here, I feel this is a bit of wisdom which definitely guides my approach.
However, I find it hard to see how adding it to the principles helps us follow them better.

**Comment by clausmullie** [comment]
Closing this pull request for now, as it's over a year old.

**Pull request closed without merging**
