### PR TITLE
Release 20201207

### PR DESCRIPTION
**Pull request by ElenaFdR**
## Review checklist template

- [x] Correct Markdown and formatting
- [x] All new files are linked in indices
- [x] Front matter is present and correct
- [x] Bullets and numbered lists are correct
- [x] All content reviewed

-----
[View rendered activities/codebase-auditing/review-template.md](https://github.com/publiccodenet/about/blob/release-20201207/activities/codebase-auditing/review-template.md)
[View rendered activities/philanthropic-fundraising/index.md](https://github.com/publiccodenet/about/blob/release-20201207/activities/philanthropic-fundraising/index.md)
[View rendered activities/staff-management/expense.md](https://github.com/publiccodenet/about/blob/release-20201207/activities/staff-management/expense.md)
[View rendered activities/tool-management/odoo.md](https://github.com/publiccodenet/about/blob/release-20201207/activities/tool-management/odoo.md)
[View rendered glossary/contractor-definition.md](https://github.com/publiccodenet/about/blob/release-20201207/glossary/contractor-definition.md)
[View rendered organization/index.md](https://github.com/publiccodenet/about/blob/release-20201207/organization/index.md)
[View rendered organization/staff.md](https://github.com/publiccodenet/about/blob/release-20201207/organization/staff.md)

### CODE REVIEW

**Review by bvhme — DISMISSED** [review]
This looks good. 

Would it be possible to version control the binary PDFs separately from this repository? A binary file it is not easily version controlled because every version is stored, not just the changes. Versioning the PDFs in this repository comes with some drawbacks, mainly that anyone cloning the project will need to download every version of that PDF. This is more of an ergonomic thing than a functional one so feel free to ignore this point.

Perhaps linking to the Figma file and letting users export (or copy and change) their version might be an idea.

**Comment by Ainali** [comment]
> Perhaps linking to the Figma file and letting users export (or copy and change) their version might be an idea.

And if we really want to serve the ready made pdf's, we could store them in our nextcloud and just link to them.

**Comment by demkodo** [comment]
> > Perhaps linking to the Figma file and letting users export (or copy and change) their version might be an idea.
> 
> And if we really want to serve the ready made pdf's, we could store them in our nextcloud and just link to them.

Nextcloud is still up and running and you all have user accounts. If you cannot access your account anymore, let me know and I'll help with resetting it. You can reach NextCloud here: https://collaboration.publiccode.net/nextcloud/

**Comment by Ainali** [comment]
If we want to move it to NextCloud, here is the file links:

* A4: https://collaboration.publiccode.net/nextcloud/index.php/s/Cb2BN2mn9jzggRz
* Letter: https://collaboration.publiccode.net/nextcloud/index.php/s/oGrom5RXzii2Zso

**Review by Ainali — APPROVED** [review]

**Review by Ainali — APPROVED** [review]

**Review by bvhme — APPROVED** [review]

**Pull request merged**
