### PR TITLE
Splitting community calls

### PR DESCRIPTION
**Pull request by Ainali**
Both in terms of Standard for Public Code vs Foundation for Public Code community and dividing it up into three parts for easier overview. Solves #504 

-----
[View rendered activities/codebase-stewardship/community-calls/index.md](https://github.com/publiccodenet/about/blob/standard-community-call/activities/codebase-stewardship/community-calls/index.md)
[View rendered activities/codebase-stewardship/community-calls/post-process-community-call.md](https://github.com/publiccodenet/about/blob/standard-community-call/activities/codebase-stewardship/community-calls/post-process-community-call.md)
[View rendered activities/codebase-stewardship/community-calls/preparing-community-call.md](https://github.com/publiccodenet/about/blob/standard-community-call/activities/codebase-stewardship/community-calls/preparing-community-call.md)
[View rendered activities/codebase-stewardship/community-calls/running-community-call.md](https://github.com/publiccodenet/about/blob/standard-community-call/activities/codebase-stewardship/community-calls/running-community-call.md)
[View rendered activities/communication/conference-call-etiquette.md](https://github.com/publiccodenet/about/blob/standard-community-call/activities/communication/conference-call-etiquette.md)
[View rendered activities/communication/run-a-community-call.md](https://github.com/publiccodenet/about/blob/standard-community-call/activities/communication/run-a-community-call.md)

### CODE REVIEW

**Comment by bvhme** [comment]
Could we merge this pull request soon @ElenaFdR?

@Ainali if you could fix the link that is breaking Travis.

**Comment by Ainali** [comment]
> Could we merge this pull request soon @ElenaFdR?
> 
> @Ainali if you could fix the link that is breaking Travis.

The link is dependent on #539, if that one gets merged, the broken link will resolve.

**Comment by bvhme** [comment]
Okay, then we should take it out of this pull request and put it in a
separate one, because now the other pull request is blocking this one
putting extra pressure onto it. We want to keep the ability to merge things
at their own tempo so we can make sure they are good.

**Comment by Ainali** [comment]
> Okay, then we should take it out of this pull request and put it in a separate one, because now the other pull request is blocking this one putting extra pressure onto it. We want to keep the ability to merge things at their own tempo so we can make sure they are good.

Okay! Deleted the link for now.

**Comment by bvhme** [comment]
@AlbaRoza if you give a thumbs up I think we should merge this as it's been blocking long enough. @ElenaFdR can go over it later.

**Pull request merged**
