### PR TITLE
Remove assessment process based on Google spreadsheets

### PR DESCRIPTION
**Pull request by Ainali**
This has been replaced by the [process in Odoo](https://about.publiccode.net/activities/codebase-stewardship/odoo-codebases.html).
We don't use these templates actively since a long time.

-----
[View rendered activities/codebase-stewardship-assessment/assessment-issue-template.md](https://github.com/publiccodenet/about/blob/remove-google-assessments/activities/codebase-stewardship-assessment/assessment-issue-template.md)
[View rendered activities/codebase-stewardship-assessment/create-assessment-spreadsheet.md](https://github.com/publiccodenet/about/blob/remove-google-assessments/activities/codebase-stewardship-assessment/create-assessment-spreadsheet.md)
[View rendered activities/codebase-stewardship-assessment/criteria-for-codebase-stewardship.md](https://github.com/publiccodenet/about/blob/remove-google-assessments/activities/codebase-stewardship-assessment/criteria-for-codebase-stewardship.md)
[View rendered activities/codebase-stewardship-assessment/index.md](https://github.com/publiccodenet/about/blob/remove-google-assessments/activities/codebase-stewardship-assessment/index.md)
[View rendered activities/codebase-stewardship-assessment/open-assessment.md](https://github.com/publiccodenet/about/blob/remove-google-assessments/activities/codebase-stewardship-assessment/open-assessment.md)
[View rendered activities/codebase-stewardship/community-assets.md](https://github.com/publiccodenet/about/blob/remove-google-assessments/activities/codebase-stewardship/community-assets.md)
[View rendered activities/codebase-stewardship/for-existing-projects.md](https://github.com/publiccodenet/about/blob/remove-google-assessments/activities/codebase-stewardship/for-existing-projects.md)
[View rendered activities/codebase-stewardship/index.md](https://github.com/publiccodenet/about/blob/remove-google-assessments/activities/codebase-stewardship/index.md)
[View rendered activities/codebase-stewardship/lifecycle.md](https://github.com/publiccodenet/about/blob/remove-google-assessments/activities/codebase-stewardship/lifecycle.md)
[View rendered activities/codebase-stewardship/odoo-codebase-template.md](https://github.com/publiccodenet/about/blob/remove-google-assessments/activities/codebase-stewardship/odoo-codebase-template.md)
[View rendered activities/codebase-stewardship/product-assets-for-early-incubation.md](https://github.com/publiccodenet/about/blob/remove-google-assessments/activities/codebase-stewardship/product-assets-for-early-incubation.md)
[View rendered activities/index.md](https://github.com/publiccodenet/about/blob/remove-google-assessments/activities/index.md)
[View rendered activities/membership-growth/membership-proposal-template.md](https://github.com/publiccodenet/about/blob/remove-google-assessments/activities/membership-growth/membership-proposal-template.md)

### CODE REVIEW

**Comment by clausmullie** [comment]
Nice one @Ainali! 

I think this pull request makes sense, as we don't use the template anymore and now have a refined set of questions we assess with in Odoo.

Two considerations before merging would be:
1) The assessment criteria page (criteria-for-codebase-stewardship.md) has a list of questions. We have iterated to make less and better questions. These questions are no longer part of our standard process. However, they may still be useful somewhere else (like as a reminder check list or resource of some sorts). @ericherman Do you see any value in keeping this list of questions somewhere, and in what form/where would you keep them?
2) The open-assessment.md page has a nice bit of process on getting the consent of maintainers and working with them in the open. We could move some of this content (or at least the spirit of it) to the codebase auditing pages.

**Comment by Ainali** [comment]
> 2\. We could move some of this content (or at least the spirit of it) to the codebase auditing pages.

Agreed! I created #1041 for that.

**Review by nebster — APPROVED** [review]
good tidying up

**Comment by ericherman** [comment]
>     1. The assessment criteria page (criteria-for-codebase-stewardship.md) has a list of questions. We have iterated to make less and better questions. These questions are no longer part of our standard process. However, they may still be useful somewhere else (like as a reminder check list or resource of some sorts). @ericherman Do you see any value in keeping this list of questions somewhere, and in what form/where would you keep them?

I think we should just prune it because I suspect that the cost of keeping them elsewhere and maintaining them there is likely to outweigh their value over time.

Also, all of this content is kept in the git history, so we can fetch them from there.

(I can help others search git history if they have need of help in doing so.)

**Review by ericherman — APPROVED** [review]

**Pull request merged**
